apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-deployment
  labels:
    app: inventory
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
      - name: inventory-container
        image: docker.io/atuljkamble/inventory-app:latest
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: acr-secret
