apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  labels:
    app: inventory
spec:
  type: LoadBalancer
  selector:
    app: inventory
  ports:
    - name: http
      port: 80           # External port (used by LoadBalancer)
      targetPort: 5000   # Container port your app listens on
